apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.state.makeline
  namespace: reddog
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
    - name: url
      secretKeyRef:
        name: cosmos-uri
        key: cosmos-uri
    - name: database
      value: reddog
    - name: collection
      value: reddogstate
    - name: masterKey
      secretKeyRef:
        name: cosmos-primary-rw-key
        key: cosmos-primary-rw-key
scopes:
  - make-line-service
auth:
  secretStore: reddog.secretstore  
