name: package-accounting-service

on:
  push:
    branches:
      - 'main'
    paths:
      - 'RedDog.AccountingService/**'

  workflow_dispatch:

jobs:
  set-env:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.main.outputs.version }}
      created: ${{ steps.main.outputs.created }}
      project: ${{ steps.main.outputs.project }}
      image: ${{ steps.main.outputs.image }}
    steps:
      - id: main
        run: |
          echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-7)
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=project::AccountingService
          echo ::set-output name=image::reddog-retail-accounting-service

  package-service:
    name: Package Service
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: RedDog.${{ needs.set-env.outputs.project }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_ENDPOINT }}/reddog-retail-demo/${{ needs.set-env.outputs.image }}:latest
            ${{ secrets.ACR_ENDPOINT }}/reddog-retail-demo/${{ needs.set-env.outputs.image }}:${{ needs.set-env.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ needs.set-env.outputs.created }}
            org.opencontainers.image.revision=${{ needs.set-env.outputs.version }}
      - name: Update deployment yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'manifests/deployments/accounting-service.yaml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: ${{ secrets.ACR_ENDPOINT }}/reddog-retail-demo/${{ needs.set-env.outputs.image }}:${{ needs.set-env.outputs.version }}
          commitChange: 'true'
          branch: 'main'
          message: 'Updated accounting service deployment manifest.'
          createPR: 'false'
          updateFile: 'true'
      - name: Echo yaml
        run: |
          cat manifests/deployments/accounting-service.yaml