apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- accounting-service.yaml
- bootstrapper.yaml
- ingress-ui.yaml
- ingress-services.yaml
- loyalty-service.yaml
- make-line-service.yaml
- order-service.yaml
- rbac.yaml
- receipt-generation-service.yaml
- services-external.yaml
- ui.yaml
- virtual-worker.yaml