apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.state.loyalty
  namespace: reddog
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-release-master.redis.svc.cluster.local:6379
    - name: redisPassword
      secretKeyRef:    
        name: redis-password
        key: redis-password
scopes:
  - loyalty-service
auth:
  secretStore: reddog.secretstore
