apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.pubsub
  namespace: reddog
spec:
  type: pubsub.azure.servicebus
  version: v1  
  metadata:
    - name: connectionString
      secretKeyRef:
        name: sb-root-connectionstring
        key: sb-root-connectionstring
scopes:
  - order-service
  - make-line-service
  - loyalty-service
  - receipt-generation-service
  - accounting-service   
auth:
  secretStore: reddog.secretstore
