apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.pubsub
  namespace: reddog
spec:
  type: pubsub.azure.servicebus
  version: v1  
  metadata:
    - name: connectionString
      secretKeyRef:
        name: reddog.secrets
        key: sb-connect-string
scopes:
  - order-service
  - make-line-service
  - loyalty-service
  - accounting-service
